### ISSUE TITLE
Failed to create a resource with args in spec

### ISSUE THREAD

**Issue by mayzhang2000** [keikoproj/kubedog#58]
Here is the test feature file:
```
Feature: install my resource

    Scenario: Install my resource

        Given valid AWS Credentials
        And a Kubernetes cluster
        And I create the resources in test.yaml
        Then the resource test.yaml should be created
```

Here is test.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: mayally0328-cpu-utilization
  namespace: app-albcanary-base
spec:
  args:
    - name: namespace
    - name: stable-hash
    - name: canary-hash
    - name: prometheus-port
    - name: cpu-utilization-limit-perc
    - name: initial-delay
      value: 1m
    - name: count
      value: "10"
    - name: interval
      value: 60s
    - name: failure-limit
      value: "1"
    - name: inconclusive-limit
      value: "1"
  metrics:
    - count: '{{args.count}}'
      failureLimit: '{{args.failure-limit}}'
      inconclusiveLimit: '{{args.inconclusive-limit}}'
      initialDelay: '{{args.initial-delay}}'
      interval: '{{args.interval}}'
      name: cpu-utilization
      provider:
        prometheus:
          address: http://prometheus.addon-metricset-ns.svc.cluster.local:{{args.prometheus-port}}
          query: (quantile(0.5, quantile_over_time(0.5, namespace_pod_cpu_utilization{namespace="{{args.namespace}}",
            pod=~".*-{{args.canary-hash}}-.*"}[11m])))
      successCondition: result[0] <= {{args.cpu-utilization-limit-perc}}
```

When running `godog features`, below error is thrown:
`ERRO[0002] Failed deleting old test resources: 'template: Resource:93: function "args" not defined' `
